version: "3.9"

services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: unless-stopped
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
    ports:
      - $MONGODB_LOCAL_PORT:$MONGODB_DOCKER_PORT
    volumes:
      - db:/data/db

  backend:
    build: ./backend
    container_name: backend
    depends_on:
      - mongodb
    restart: unless-stopped
    env_file: .env
    ports:
      - $BACKEND_LOCAL_PORT:$BACKEND_DOCKER_PORT
    environment:
      - DB_HOST=mongodb
      - DB_USER=$MONGODB_USER
      - DB_PASSWORD=$MONGODB_PASSWORD
      - DB_NAME=$MONGODB_DATABASE
      - DB_PORT=$MONGODB_DOCKER_PORT
      - BACKEND_DOCKER_PORT=$BACKEND_DOCKER_PORT
      - NODE_ENV=production

  frontend:
    build: ./frontend
    container_name: frontend
    depends_on:
      - backend
    restart: unless-stopped
    env_file: .env
    ports:
      - $FRONTEND_LOCAL_PORT:3000
    environment:
      - NEXT_PUBLIC_BACKEND_URL=$NEXT_PUBLIC_BACKEND_URL
volumes:
  db:
